# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ytfm7v9V6QY1KOdWNcYCX4WVp2Au1Zoo
"""

"""# New Section"""

from datetime import datetime
import requests
import pandas as pd
from bs4 import BeautifulSoup

# Steam Top Sellers page
url = "https://store.steampowered.com/search/?filter=topsellers"

# Add a browser-like header so Steam is less likely to block the request
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0 Safari/537.36"
    )
}

response = requests.get(url, headers=headers, timeout=20)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

rows = []

# Each game result is inside an <a class="search_result_row">
games = soup.select("a.search_result_row")[:10]   # top 10 only
scrape_time = datetime.now().isoformat()
for game in games:

    # Title
    title_tag = game.select_one(".title")
    title = title_tag.get_text(strip=True) if title_tag else None

    # Price
    price_tag = game.select_one(".discount_final_price")
    if not price_tag:
        price_tag = game.select_one(".search_price")

    price = price_tag.get_text(" ", strip=True) if price_tag else None

    # Discount %
    discount_tag = game.select_one(".discount_pct")
    discount = discount_tag.get_text(strip=True) if discount_tag else None

    # Release date
    release_tag = game.select_one(".search_released")
    release_date = (
        release_tag.get_text(strip=True) if release_tag else None
    )

    # Platforms (Windows / Mac / Linux)
    platform_icons = game.select(".platform_img")
    platforms = [
        icon["class"][-1]
        for icon in platform_icons
        if len(icon.get("class", [])) > 1
    ]

    rows.append({
        "title": title,
        "price_tag": price_eur,
        "discount": discount,
        "release_date": release_date,
        "platforms": ", ".join(platforms),
        "scraped_at": scrape_time,
    })

# Create DataFrame
df = pd.DataFrame(rows)

# Show result

# Optional: save to CSV
df.to_csv("steam_top_10_bestsellers.csv", index=False, mode='w')

"""# New Section"""

# Check what your DataFrame looks like right now
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")


"""# New Section"""

# See how many missing values exist per column


# The 'rating' column does not exist in the current DataFrame scraped from Steam,
# so the following line is removed.
# df["rating"] = df["rating"].fillna("Unknown")

"""# New Section"""

# Identify current column names
current_columns = df.columns.tolist()

# Create a new list of column names, renaming the first 'price_eur' to 'price_usd'
new_columns = []
first_price_eur_found = False

for col_name in current_columns:
    if col_name == 'price_eur' and not first_price_eur_found:
        new_columns.append('price_usd')
        first_price_eur_found = True
    else:
        new_columns.append(col_name)

df.columns = new_columns
 # verify the renamed columns
df

"""# New Section"""

# Final check
print(f"Rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nSample:")
df.head()

df.to_csv("verify_output.csv", index=False)
print(f"Rows: {len(df)}  |  Columns: {list(df.columns)}")
df

# Add a price tier for dashboard grouping
# .apply() runs a function on every value in the column
# The lambda checks: is the price below 20? → "Budget"
#                     below 40? → "Mid-range"
#                     otherwise → "Premium"
df["price_tier"] = df["price_eur"].apply(
    lambda p: "Budget" if p < 30
    else ("Mid-range" if p < 50 else "Premium")
)

df[["title", "price_eur", "price_tier"]]


df["price_tier"] = df["price_eur"].apply(
    lambda p: "Budget" if p < 20
    else ("Mid-range" if p < 40 else "Premium")
)

df[["title", "price_eur", "price_tier"]]

# Example: drop the raw price string (you already have price_eur)
# errors="ignore" means: if the column does not exist, do nothing
df = df.drop(columns=["price_raw"], errors="ignore")

 # verify which columns remain


from supabase import create_client
from datetime import datetime

SUPABASE_URL = os.environ["https://jkgppebuejneksmouaup.supabase.co"]   # your Project URL
SUPABASE_KEY = os.environ["sb_publishable_cfSp7j6BBRTxAUDy8ELVqQ_7mtwTnZF"]              # your anon/public key

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()

rows = []
for _, row in df.iterrows():
    rows.append({
        "title":        str(row.get("title", "")),
        "price_usd":    float(row.get("price_usd", 0)),
        "discount":  str(row.get("discount", "%")),
        "release_date": str(row.get("release_date", "")),
        "platforms": str(row.get("platforms", "")),
        "price_eur": str(row.get("price_eur", "")),
        "price_eur_formatted": str(row.get("price_eur_formatted", "")),
    })

result = supabase.table("Games").insert(rows).execute()
print(f"✅ Inserted {len(rows)} rows into Supabase")




from supabase import create_client
from datetime import datetime

SUPABASE_URL = "https://etntvokrvtlqjvfqjpkz.supabase.co"   # your Project URL
SUPABASE_KEY = "sb_publishable_fLrEwzdyJzZ5iTPWrr6e3g_0xaHvAig"              # your anon/public key

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()

rows = []
for _, row in df.iterrows():
    rows.append({
        "title":        str(row.get("title", "")),
        "price_usd":    float(row.get("price_usd", 0)),
        "discount":  str(row.get("discount", "%")),
        "release_date": str(row.get("release_date", "")),
        "platforms": str(row.get("platforms", "")),
        "price_eur": str(row.get("price_eur", "")),
        "price_eur_formatted": str(row.get("price_eur_formatted", "")),
    })

result = supabase.table("steam").insert(rows).execute()
print(f"✅ Inserted {len(rows)} rows into Supabase")
